# Generated by Django 5.2.8 on 2025-12-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kg'), ('SACK', 'Sack'), ('BOX', 'Box')], default='KG', max_length=10),
        ),
    ]
