from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('create/', views.create_listing, name='create_listing'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:listing_id>/', views.cart_add, name='cart_add'),
    path('cart/update/<int:listing_id>/', views.cart_update, name='cart_update'),
    path('cart/remove/<int:listing_id>/', views.cart_remove, name='cart_remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('dashboard/', views.farmer_dashboard, name='farmer_dashboard'),
    path('farmer/orders/', views.farmer_orders, name='farmer_orders'),
    path('farmer/<str:username>/', views.farmer_profile, name='farmer_profile'),
    path('message/send/<str:recipient_username>/', views.send_message, name='send_message'),
    path('inbox/', views.inbox, name='inbox'),
    path('listing/id/<int:pk>/', views.edit_listing, name='edit_listing'),
    path('listing/delete/<int:pk>/', views.delete_listing, name='delete_listing'),
    path('orders/', views.consumer_orders, name='consumer_orders'),
    path('my-orders/', views.buyer_orders, name='buyer_orders'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('profile/', views.profile, name='profile'),
    path('order/update/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('profile/public/<str:username>/', views.user_profile_public, name='user_profile_public'),
    path('analytics/', views.farmer_analytics, name='farmer_analytics'),
    path('analytics/download/', views.download_sales_report, name='download_sales_report'),
    path('farmers/nearby/', views.nearby_farmers, name='nearby_farmers'),
    path('api/mpesa/callback/<int:order_id>/', views.mpesa_callback, name='mpesa_callback'),
    path('api/notifications/check/', views.check_notifications, name='check_notifications'),
    path('notifications/read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('wishlist/toggle/<int:listing_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    path('portal/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('portal/users/', views.manage_users, name='manage_users'),
    path('portal/users/delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path('portal/users/verify/<int:user_id>/', views.toggle_verification, name='toggle_verification'),
    path('portal/users/warn/<int:user_id>/', views.warn_user, name='warn_user'),
    path('appeal/', views.submit_appeal, name='submit_appeal'),
    path('portal/users/ban/<int:user_id>/', views.ban_user, name='ban_user'),
    path('portal/users/unban/<int:user_id>/', views.unban_user, name='unban_user'),
    path('portal/listings/', views.manage_listings, name='manage_listings'),
    path('portal/listings/delete/<int:listing_id>/', views.delete_listing, name='delete_listing'),
    path('portal/orders/', views.manage_orders, name='manage_orders'),
    path('portal/categories/', views.manage_categories, name='manage_categories'),
    path('portal/categories/delete/<int:category_id>/', views.delete_category, name='delete_category'),
    path('portal/logs/', views.activity_logs, name='activity_logs'),
    
    # Reporting
    path('report/<int:user_id>/', views.submit_report, name='submit_report'),
    path('portal/reports/', views.manage_reports, name='manage_reports'),
    path('portal/reports/resolve/<int:report_id>/', views.resolve_report, name='resolve_report'),
]
